### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by altercode** [Shoplo/shoplo-php-v2#2]
Hi,

I have problem with authentication with shoplo api. I have successfully run this repository 
on local computer and connect it to created test app in shoplo panel. 
When I run the application I am redirected to login page (and this is correct).
After successfully login I'm redirected to callback url (http://shoplo-app/example.php) and I can see a list of products from the example. But after I hit refresh button in the browser I'm redirected back to login page. Shouldn't I stay on the same page instead? It seems that my credentials are not stored in the session.

Can someone point me into right direction why I'm constantly redirected to shoplo login page?

Thanks in advanced!

**Comment by AdrianAdamiec** [comment]
Hi,

in order to maintain authentication You need to store oauth_token and oauth_token_secret in your own storage such as session, db or similar. Then pass your credentials to initClient and proceed with your requests.

**Comment by altercode** [comment]
Ok, It helped. Thanks!
