### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by Buzka91** [Shoplo/shoplo-php-v2#3]
Hello!

I would like to use this package, but my minimum-stability composer block it. Could you create v1.0 release/tag?
(composer take versions from https://packagist.org/packages/shoplo/clientv2 site)

**Comment by piotrantosik** [comment]
Hi @Buzka91!
Thanks for reporting,
please use https://github.com/Shoplo/store-client which is in stable version

**Comment by Buzka91** [comment]
Official library for PHP is linked to this package (https://docs.shoplo.com/api/library/php). Web is not up-to-date?
